config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/toys", to: "toys#index", as: "toys" #show all toys
  post "/toys", to: "toys#create" #create a new toys
  get "/toys/new", to: "toys#new", as: "new_toy" #new form
  get "/toys/:id", to: "toys#show", as: "toy" #show single toy
  put "/toys/:id", to: "toys#update"
  patch "/toys/:id", to: "toys#update"
  get "/toys/:id/edit", to: "toys#edit", as: "edit_toy" 
  delete "/toys/:id", to: "toys#destroy"

  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/toys_controller.rb
class ToysController < ApplicationController
  before_action :find_toy, only: [:show, :edit, :update, :destroy] 
  def index
    @toys = Toy.all
  end

  def create
    @toy = Toy.create(toy_params)
    redirect_to @toy
  end

  def new
  end

  def show
  end

  def edit
  end

  def update
    @toy.update(toy_params)
    redirect_to @toy
  end

  def destroy
    @toy.destroy
    redirect_to root_path
    
  end

  private
  def find_toy
    @toy = Toy.find(params[:id])
  end

  def toy_params 
      params.require(:toy).permit(:name, :date, :user)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toys_helper.rb
module ToysHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/toys/edit.html.erb
<h1>Edit A Toy</h1>

<form action="<%= toy_path(@toy.id) %>" method="POST">

 <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" /> 


<input type="hidden" name="_method" value="patch" /> 

    <label for="name">Name</label>
    <input type="text" name="toy[name]" id="name" value="<%= @toy.name %>"   />

    <label for="date">Date Created</label>
    <input type="date"  name="toy[date]" id="date" value="<%= @toy.date %>"    />

    <label for="user">User</label>
    <input type="text"   name="toy[user]" id="user" value="<%= @toy.user %>"  />


   <input type="submit" value="Update"/>

</form> 

app/views/toys/index.html.erb
<h1>Toys Shop</h1>

  
<div class="card-container">
      <% @toys.each do |toy| %>
      <div class="card">
        
          <h3>Name: <%=  toy.name %> </h3>
          <h3>Date Created: <%= toy.date %> </h3>
          <h3>User: <%= toy.user %>   </h3>
        
        
          <%= link_to "Update", edit_toy_path(toy.id) %>
          <%= link_to "Show", toy_path(toy.id) %>
          <%= link_to "Delete", toy_path(toy.id), method: :delete, data: { confirm: "Are you sure?" } %>
        
      </div>  
        <% end %> 
</div>  

app/views/toys/new.html.erb
<h1>Add A New toy</h1>

<form action="<%= toys_path %>" method ="POST">

  <input type="hidden" value="<%= form_authenticity_token %>" name="authenticity_token" /> 

    <label for="name">Name</label>
    <input type="text" name="toy[name]" id="name"   />

    <label for="date">Date created</label>
    <input type="date"  name="toy[date]" id="date"   />

    <label for="user">User</label>
    <input type="text" name="toy[user]" id="user"   />

   <input type="submit" value="Create New Toy"/>

</form> 
    

app/views/toys/show.html.erb
<h3>Name:<%=@toy.name %> </h3>
<h3>Date Created: <%= @toy.date %></h3>
<h3>User: <%= @toy.user %></h3>
<%= link_to "Back", toys_path %>

app/views/welcome/index.html.erb
<h1>Welcome To Toy Shop</h1>

<h3><%= link_to "View All Toys", toys_path %> </h3>
<h3><%= link_to "Create A Toy", new_toy_path %></h3>